CREATE TABLE CARGO
(CODIGO_CARGO NUMBER NOT NULL,
NOME_CARGO VARCHAR2(100) NOT NULL,
SALARIO NUMBER(12,2) NOT NULL,
CONSTRAINT PK_CODIGO_CARGO PRIMARY KEY (CODIGO_CARGO));

CREATE TABLE DEPARTAMENTO
(SIGLA_DEPARTAMENTO CHAR(3) NOT NULL,
NOME_DEPARTAMENTO VARCHAR2(50) NOT NULL,
MATRICULA_CHEFE NUMBER NOT NULL,
CONSTRAINT PK_SIGLA_DEPARTAMENTO PRIMARY KEY (SIGLA_DEPARTAMENTO));

CREATE TABLE FUNCIONARIO
(MATRICULA_FUNC NUMBER NOT NULL,
NOME VARCHAR2(100) NOT NULL,
IDENTIDADE VARCHAR2(9) NULL,
CPF VARCHAR2(11) NOT NULL,
DATA_NASCIMENTO DATE NOT NULL,
SEXO CHAR(1) NOT NULL,
LOGRADOURO VARCHAR2(100) NULL,
BAIRRO VARCHAR2(50) NULL,
CIDADE VARCHAR2(50) NULL,
UF CHAR(2) NULL,
CODIGO_CARGO NUMBER NOT NULL,
SIGLA_DEPARTAMENTO CHAR(3) NOT NULL,
MATRICULA_SUPERVISOR NUMBER NULL,
CONSTRAINT PK_MATRICULA_FUNC PRIMARY KEY (MATRICULA_FUNC),
CONSTRAINT FK_CODIGO_CARGO_FUNCIONARIO FOREIGN KEY (CODIGO_CARGO) REFERENCES CARGO (CODIGO_CARGO),
CONSTRAINT FK_SIGLA_DEPT_FUNC FOREIGN KEY (SIGLA_DEPARTAMENTO) REFERENCES DEPARTAMENTO (SIGLA_DEPARTAMENTO),
CONSTRAINT FK_MAT_SUPERVISOR_FUNCIONARIO FOREIGN KEY (MATRICULA_SUPERVISOR) REFERENCES FUNCIONARIO (MATRICULA_FUNC));

ALTER TABLE DEPARTAMENTO ADD
(CONSTRAINT FK_MATRICULA_CHEFE FOREIGN KEY (MATRICULA_CHEFE) REFERENCES FUNCIONARIO (MATRICULA_FUNC));

CREATE TABLE DEPENDENTE
(NUM_REGISTRO NUMBER NOT NULL,
MATRICULA_FUNC NUMBER NOT NULL,
NOME VARCHAR2(100) NOT NULL,
DATA_NASCIMENTO DATE NOT NULL,
CONSTRAINT PK_DEPENDENTE PRIMARY KEY (NUM_REGISTRO, MATRICULA_FUNC),
CONSTRAINT FK_MATRICULA_FUNC FOREIGN KEY (MATRICULA_FUNC) REFERENCES FUNCIONARIO (MATRICULA_FUNC));

CREATE TABLE PROJETO
(CODIGO_PROJETO NUMBER NOT NULL,
NOME_PROJETO VARCHAR2(100) NOT NULL,
CUSTO_PREVISTO NUMBER(12,2) NULL,
PREVISAO_DERACAO_MESES NUMBER(3) NULL,
SIGLA_DEPARTAMENTO_RESP CHAR(3) NULL,
CONSTRAINT PK_CODIGO_PROJETO PRIMARY KEY (CODIGO_PROJETO),
CONSTRAINT FK_SIGLA_DEPARTAMENTO_RESP FOREIGN KEY (SIGLA_DEPARTAMENTO_RESP) REFERENCES DEPARTAMENTO (SIGLA_DEPARTAMENTO));


CREATE TABLE ALOCACAO_FUNC_PROJETO
(MATRICULA_FUNC NUMBER NOT NULL,
CODIGO_PROJETO NUMBER NOT NULL,
DATA_INICIO DATE NOT NULL,
DATA_FIM DATE NULL,
CONSTRAINT PK_ALOC_FUNC_PROJ PRIMARY KEY (DATA_INICIO,MATRICULA_FUNC,CODIGO_PROJETO),
CONSTRAINT FK_FUNC_ALOC_PROJETO FOREIGN KEY (MATRICULA_FUNC) REFERENCES FUNCIONARIO (MATRICULA_FUNC),
CONSTRAINT FK_CODIGO_PROJETO FOREIGN KEY (CODIGO_PROJETO) REFERENCES PROJETO (CODIGO_PROJETO));
