ALTER TABLE FUNCIONARIO
ADD DATA_ADMISSAO DATE NULL,

ALTER TABLE FUNCIONARIO MODIFY
 (IDENTIDADE VARCHAR2(9),
 CPF VARCHAR2(11))

ALTER TABLE CARGO ADD
(DATA_CRIACAO DATE NOT NULL,
DATA_ULT_ATUALIZACAO DATE NULL);

ALTER TABLE DEPARTAMENTO ADD
(DATA_CRIACAO DATE NOT NULL,
DATA_ULT_ATUALIZACAO DATE NULL);

ALTER TABLE PROJETO ADD
(DATA_CRIACAO DATE NOT NULL,
DATA_ULT_ATUALIZACAO DATE NULL);

CREATE TABLE ESCOLARIDADE
(CODIGO NUMBER(2) NOT NULL,
DESCRICAO VARCHAR(30) NOT NULL,
CONSTRAINT PK_CODIGO PRIMARY KEY (CODIGO));

AlTER TABLE DEPENDENTE ADD (CODIGO_ESCOLARIDADE NUMBER(2) NOT NULL);

ALTER TABLE DEPENDENTE ADD CONSTRAINT FK_CODIGO_ESCOLARIDADE FOREIGN KEY
(CODIGO_ESCOLARIDADE) REFERENCES ESCOLARIDADE (CODIGO);

ALTER TABLE CARGO DROP (DATA_CRIACAO, DATA_ULT_ATUALIZACAO);
ALTER TABLE DEPARTAMENTO DROP (DATA_CRIACAO, DATA_ULT_ATUALIZACAO);
ALTER TABLE PROJETO DROP (DATA_CRIACAO, DATA_ULT_ATUALIZACAO);

ALTER TABLE DEPARTAMENTO DROP (MATRICULA_CHEFE);

ALTER TABLE DEPENDENTE DROP COLUMN CODIGO_ESCOLARIDADE;
DROP TABLE ESCOLARIDADE;

