4.1 - UPDATE CARGO
SET NOME_CARGO = 'Representante Comercial'
WHERE NOME_CARGO = 'Vendedor';

4.2 - UPDATE CARGO
SET SALARIO = SALARIO * 1.10
WHERE NOME_CARGO = 'Engenheiro';

4.3 - UPDATE CARGO
SET DATA_NASCIMENTO = '10/09/1978'
WHERE MATRICULA_FUNC = 34732;

4.4 - UPDATE FUNCIONARIO
SET BAIRRO = 'Ouro Verde'
CIDADE = 'Rio das Ostras'
WHERE CEP = 25890010;

4.5 - UPDATE FUNCIONARIO
SET SIGLA_DEPARTAMENTO = 'TI'
WHERE NOME = 'Carlos Alberto da Rocha';

4.6 - UPDATE ALOCACAO_FUNC_PROJETO
SET DATA_INICIO = '01/03/2013'
WHERE DATA_INICIO = '29/02/2013' AND DATA_FIM IS NULL;

4.7 - UPDATE FUNCIONARIO
SET SIGLA_DEPARTAMENTO = 'ENG'
WHERE SEXO = 'M';

4.8 - UPDATE PROJETO
SET SIGLA_DEPARTAMENTO_RESP = 'ADM'
WHERE CUSTO_PREVISTO > 10000;

4.9 - UPDATE DEPARTAMENTO
SET MATRICULA_CHEFE = '386'
WHERE SIGLA_DEPARTAMENTO = 'MKT';

COMMIT;

5.1 - DELETE FROM CARGO WHERE NOME_CARGO = 'Analista Pleno';

5.2 - DELETE FROM DEPENDENTE WHERE DATA_NASCIMENTO < '01/01/1990';

5.3 - DELETE FROM DEPENDENTE WHERE MATRICULA_FUNC = (SELECT MATRICULA_FUNC FROM FUNCIONARIO WHERE NOME = 'CARLOS ALBERTO DA ROCHA');

5.4 - DELETE FROM PROJETO WHERE CUSTO_PREVISTO > 300000 AND SIGLA_DEPARTAMENTO_RESP IS NULL;

5.5 - DELETE FROM FUNCIONARIO WHERE MATRICULA_FUNC NOT IN (SELECT MATRICULA_FUNC FROM ALOCACAO_FUNC_PROJETO);

COMMIT;