7.1 - SELECT UPPER(F.NOME), LOWER (D.NOME) 
FROM FUNCIONARIO F, DEPENDENTE D
WHERE D.MATRICULA_FUNC = F.MATRICULA_FUNC


7.2 - SELECT BAIRRO || ' - ' || CIDADE || ' - ' || UF
FROM FUNCIONARIO


7.3 - SELECT RPAD(NOME_CARGO, LENGTH(NOME_CARGO)) FROM CARGO 
WHERE SALARIO > 2000


7.4 - SELECT NOME FROM FUNCIONARIO
WHERE LENGTH(NOME) = (SELECT MAX(LENGTH(NOME)) FROM FUNCIONARIO)

7.5 - UPDATE CARGO
SET NOME_CARGO = REPLACE (NOME_CARGO, 'Analist', 'Analista De Sistemas');
COMMIT;

7.6 - ##########################################################

7.7 - SELECT F.NOME, 'R$' || TRUNC(C.SALARIO)
FROM CARGO C INNER JOIN FUNCIONARIO F
ON F.CODIGO_CARGO = C.CODIGO_CARGO

7.8 - SELECT D.NOME_DEPARTAMENTO, AVG(C.SALARIO)
FROM DEPARTAMENTO D
INNER JOIN FUNCIONARIO F
ON D.SIGLA_DEPARTAMENTO = F.SIGLA_DEPARTAMENTO
INNER JOIN CARGO C
ON F.CODIGO_CARGO = C.CODIGO_CARGO
GROUP BY D.NOME_DEPARTAMENTO
ORDER BY D.NOME_DEPARTAMENTO

7.9 - SELECT TO_CHAR(SYSDATE,'DD-MM-YYYY HH24:MI') "DATA DO SERVIDOR" FROM DUAL


7.10 - SELECT P.NOME_PROJETO, TRUNC(MAX(MONTHS_BETWEEN(A.DATA_FIM, A.DATA_INICIO)))
FROM PROJETO P INNER JOIN ALOCACAO_FUNC_PROJETO A 
ON P.CODIGO_PROJETO = A.CODIGO_PROJETO
WHERE A.DATA_FIM IS NOT NULL
GROUP BY P.NOME_PROJETO


7.11 - SELECT P.NOME_PROJETO, MAX(LAST_DAY(A.DATA_FIM))
FROM PROJETO P INNER JOIN ALOCACAO_FUNC_PROJETO A 
ON P.CODIGO_PROJETO = A.CODIGO_PROJETO
WHERE A.DATA_FIM IS NOT NULL
GROUP BY P.NOME_PROJETO

7.12 - SELECT P.NOME_PROJETO, MAX(DATA_FIM - DATA_INICIO) "Dias Decorridos"
FROM PROJETO P INNER JOIN ALOCACAO_FUNC_PROJETO A 
ON P.CODIGO_PROJETO = A.CODIGO_PROJETO
WHERE A.DATA_FIM IS NOT NULL
GROUP BY P.NOME_PROJETO

7.13 - SELECT P.NOME_PROJETO, MIN(DATA_INICIO)
FROM PROJETO P INNER JOIN ALOCACAO_FUNC_PROJETO A 
ON P.CODIGO_PROJETO = A.CODIGO_PROJETO
WHERE A.DATA_FIM IS NOT NULL
GROUP BY P.NOME_PROJETO

7.14 - SELECT SUBSTR(F.CPF,1,3) || '.' || SUBSTR(F.CPF,4,3) || '.' || SUBSTR(F.CPF,7,3) || '-' || SUBSTR(F.CPF,10) "CPF",
SUBSTR(F.IDENTIDADE,1,2) || '.' || SUBSTR(F.IDENTIDADE,3,3) || '.' || SUBSTR(F.IDENTIDADE,6,3) || '-' || SUBSTR(F.IDENTIDADE,9) "IDENTIDADE",
'R'||TO_CHAR(C.SALARIO,'FM$999999999999.99') "SALÁRIO",
BAIRRO || ', ' || CIDADE || ', ' || UF "ENDEREÇO"
FROM FUNCIONARIO F INNER JOIN CARGO C 
ON F.CODIGO_CARGO = C.CODIGO_CARGO

7.15 - SELECT F.NOME, NVL(D.NOME,'NÃO POSSUI DEPENDENTES') "DEPENDENTES"
FROM FUNCIONARIO F LEFT JOIN DEPENDENTE D
ON F.MATRICULA_FUNC = D.MATRICULA_FUNC

7.16 - SELECT MIN(SALARIO), MAX (SALARIO) FROM CARGO

7.17 - SELECT F.NOME, COUNT(A.CODIGO_PROJETO) "PROJETOS A PARTIR DE 2010"
FROM FUNCIONARIO F INNER JOIN ALOCACAO_FUNC_PROJETO A
ON F.MATRICULA_FUNC = A.MATRICULA_FUNC
WHERE A.DATA_INICIO >= '01/01/2010'
GROUP BY F.NOME

7.19 - SELECT NOME FROM FUNCIONARIO 
WHERE SIGLA_DEPARTAMENTO = (SELECT SIGLA_DEPARTAMENTO FROM FUNCIONARIO WHERE NOME = 'João da Silva Ribeiro')

7.20 - SELECT F.NOME, COUNT(A.CODIGO_PROJETO) "PROJETOS TRABALHADOS EM 2014"
FROM FUNCIONARIO F INNER JOIN ALOCACAO_FUNC_PROJETO A
ON F.MATRICULA_FUNC = A.MATRICULA_FUNC
WHERE TO_CHAR(A.DATA_INICIO,'YYYY') <= '2014' 
AND (TO_CHAR(A.DATA_FIM,'YYYY') >= 2014 OR A.DATA_FIM IS NULL)
GROUP BY F.NOME