6.1 - SELECT F.NOME, C.NOME_CARGO, D.NOME_DEPARTAMENTO 
FROM FUNCIONARIO F, CARGO C, DEPARTAMENTO D
WHERE F.SIGLA_DEPARTAMENTO = D.SIGLA_DEPARTAMENTO AND F.CODIGO_CARGO = C.CODIGO_CARGO;

6.2 - SELECT F.NOME, D.NOME
FROM FUNCIONARIO F
LEFT JOIN DEPENDENTE D
ON F.MATRICULA_FUNC = D.MATRICULA_FUNC;

6.3 - SELECT F.NOME, D.NOME
FROM FUNCIONARIO F
INNER JOIN DEPENDENTE D
ON F.MATRICULA_FUNC = D.MATRICULA_FUNC
WHERE TRUNC((MONTHS_BETWEEN(TO_DATE(SYSDATE,'DD/MM/YYYY'),TO_DATE(D.DATA_NASCIMENTO,'DD/MM/YYYY')))/12) > 10;


6.4 - SELECT S.NOME, F.NOME
FROM FUNCIONARIO S
INNER JOIN FUNCIONARIO F
ON S.MATRICULA_FUNC = F.MATRICULA_SUPERVISOR;
 
6.5 - SELECT F.NOME, P.NOME_PROJETO
FROM FUNCIONARIO F
INNER JOIN ALOCACAO_FUNC_PROJETO A
ON F.MATRICULA_FUNC = A.MATRICULA_FUNC
INNER JOIN PROJETO P
ON A.CODIGO_PROJETO = P.CODIGO_PROJETO
WHERE A.DATA_INICIO > '01/01/2010';

6.6 - SELECT F.NOME, P.NOME_PROJETO
FROM FUNCIONARIO F
LEFT JOIN ALOCACAO_FUNC_PROJETO A
ON F.MATRICULA_FUNC = A.MATRICULA_FUNC
LEFT JOIN PROJETO P
ON A.CODIGO_PROJETO = P.CODIGO_PROJETO;

6.7 - SELECT P.NOME_PROJETO, D.NOME_DEPARTAMENTO
FROM PROJETO P
INNER JOIN DEPARTAMENTO D
ON P.SIGLA_DEPARTAMENTO_RESP = D.SIGLA_DEPARTAMENTO;

6.8 - SELECT P.NOME_PROJETO, NVL(D.NOME_DEPARTAMENTO, 'SEM RESPONSÁVEL')
FROM PROJETO P
LEFT JOIN DEPARTAMENTO D
ON P.SIGLA_DEPARTAMENTO_RESP = D.SIGLA_DEPARTAMENTO;

6.9 - SELECT F.NOME, C.NOME_CARGO, D.NOME_DEPARTAMENTO, P.NOME_PROJETO
FROM FUNCIONARIO F 
LEFT JOIN CARGO C
ON F.CODIGO_CARGO = C.CODIGO_CARGO
LEFT JOIN ALOCACAO_FUNC_PROJETO A
ON F.MATRICULA_FUNC = A.MATRICULA_FUNC
LEFT JOIN PROJETO P
ON A.CODIGO_PROJETO = P.CODIGO_PROJETO
LEFT JOIN DEPARTAMENTO D
ON F.SIGLA_DEPARTAMENTO = D.SIGLA_DEPARTAMENTO
WHERE A.DATA_FIM IS NULL;

6.10 - SELECT P.NOME_PROJETO, D.NOME_DEPARTAMENTO
FROM PROJETO P
FULL OUTER JOIN DEPARTAMENTO D
ON P.SIGLA_DEPARTAMENTO_RESP = D.SIGLA_DEPARTAMENTO

6.11 - Nenhuma
