1)
CREATE TABLE EQUIPAMENTO
(CODIGO_EQPTO NUMBER NOT NULL,
NOME_EQPTO VARCHAR2(50) NOT NULL,
LOCALIZACAO_EQPTO VARCHAR2(20) NOT NULL,
VALOR_EQPTO NUMBER(12,2) NOT NULL,
CODIGO_TIPO_EQTO NUMBER(1) NOT NULL,
CONSTRAINT PK_CODIGO_EQPTO PRIMARY KEY (CODIGO_EQPTO),
CONSTRAINT FK_CODIGO_TIPO_EQTO FOREIGN KEY (CODIGO_TIPO_EQTO) REFERENCES TIPO_EQUIPAMENTO (CODIGO_TIPO_EQTO));

CREATE TABLE OPERACAO
(CODIGO_EQPTO NUMBER NOT NULL,
CPF VARCHAR2(11) NOT NULL,
DATA_INICIO DATE NOT NULL,
DATA_FIM DATE NULL,
CONSTRAINT FK_CODIGO_EQPTO FOREIGN KEY (CODIGO_EQPTO) REFERENCES EQUIPAMENTO (CODIGO_EQPTO),
CONSTRAINT FK_CPF FOREIGN KEY (CPF) REFERENCES OPERADOR (CPF),
PRIMARY KEY (DATA_FIM, CODIGO_EQPTO, CPF));


2)
ALTER TABLE EQUIPAMENTO ADD
(QUANT_ATUAL NUMBER(3) NULL,
DATA_CADASTRO DATE NULL,
DATA_ULT_ATUALIZACAO DATE NULL);


3)
ALTER TABLE OPERADOR DROP (TEMPO_EXPERIENCIA);


4)
CREATE SEQUENCE SQ_TIPO_EQUIPAMENTO
START WITH 1
INCREMENT BY 1
MAXVALUE 999
NOCACHE
NOCYCLE;

INSERT INTO TIPO_EQUIPAMENTO VALUES (SQ_TIPO_EQUIPAMENTO.NEXTVAL, 'SUBMARINO');

INSERT INTO TIPO_EQUIPAMENTO VALUES (SQ_TIPO_EQUIPAMENTO.NEXTVAL, 'TERRESTRE');

INSERT INTO TIPO_EQUIPAMENTO VALUES (SQ_TIPO_EQUIPAMENTO.NEXTVAL, 'HIBRIDO');

COMMIT;

INSERT INTO OPERADOR VALUES ('02330162620', 'CARLOS ALBERTO DA ROCHA', 'M', '01/01/2010', 12, 'ENG');
INSERT INTO OPERADOR VALUES ('86536345810', 'JOANNA DA COSTA', 'F', '22/05/2015', 6, 'OPE');
INSERT INTO OPERADOR VALUES ('05121522009', 'PEDRO HENRIQUE DOS SANTOS', 'M', '04/02/2018', 27, 'MAN');

COMMIT;

5)
DELETE FROM OPERADOR WHERE CPF NOT IN (SELECT DISTINCT CPF FROM OPERACAO) AND DATA_ADMISSAO BETWEEN '01/01/2010' AND '31/12/2016';

COMMIT;


6)
UPDATE OPERACAO
SET DATA_FIM = SYSDATE
WHERE CPF = (SELECT O.CPF
FROM OPERACAO O
LEFT JOIN OPERADOR P
ON O.CPF = P.CPF
LEFT JOIN GERENCIA G
ON P.SIGLA_GERENCIA = G.SIGLA
WHERE G.NOME = 'GESTÃO DE EQUIP SUBMARINOS') AND DATA_FIM IS NULL;

COMMIT;

7)
A restrição de integridade referencial é uma restrição para garantir que certas colunas de uma tabela qualquer estejam ligadas às chaves
primárias das tabelas as quais ela possui uma ligação. Isso é feito para que as tabelas possam ser relacionadas corretamente ou 
para que não sejam criadas fora de ordem.

8)
UPDATE EQUIPAMENTO 
SET  VALOR_EQPTO = VALOR_EQPTO * 1.2 
WHERE CODIGO_TIPO_EQTO = (SELECT E.CODIGO_TIPO_EQTO 
FROM EQUIPAMENTO E
LEFT JOIN TIPO_EQUIPAMENTO T
ON E.CODIGO_TIPO_EQTO = T.CODIGO_TIPO_EQTO 
WHERE T.NOME_TIPO_EQPTO = 'TERRESTRE') AND LOCALIZACAO_EQPTO IN ('P-55', 'P-56', 'P-62', 'P-65');

COMMIT;

