1)
CREATE OR REPLACE TRIGGER TRG_LOG_EQP
AFTER INSERT OR DELETE OR UPDATE OF VALOR_EQPTO ON EQUIPAMENTO
FOR EACH ROW
BEGIN
 IF INSERTING THEN INSERT INTO LOG_ALTERACAO_EQPTO VALUES (:NEW.COD_EQPTO, SYSDATE, LOCALTIMESTAMP, 'INSERÇÃO', USER, NULL, :NEW.VALOR_EQPTO);

ELSIF UPDATING THEN INSERT INTO LOG_ALTERACAO_EQPTO VALUES (:NEW.COD_EQPTO, SYSDATE, LOCALTIMESTAMP, 'ATUALIZAÇÃO', USER, :OLD.VALOR_EQPTO, :NEW.VALOR_EQPTO);

ELSIF DELETING THEN INSERT INTO LOG_ALTERACAO_EQPTO VALUES (:NEW.COD_EQPTO, SYSDATE, LOCALTIMESTAMP, 'EXCLUSÃO', USER, :OLD.VALOR_EQPTO, 'EQUIPAMENTO EXCLUÍDO');

END IF;
END;

2)SELECT NOME_EQPTO, VALOR_EQPTO AS VALOR_EM_REAIS, VALOR_EQPTO * (SELECT FATOR_CONV FROM CONVERSAO WHERE NOME = DOLAR) AS VALOR_EM_DOLAR
FROM EQUIPAMENTO

3)Padrão ANSI:
SELECT O.NOME AS OPERADOR, NVL(TO_CHAR(MONTHS_BETWEEN(OP.DATA_FIM, OP.DATA_INICIO)), 'NÃO REALIZOU OPERAÇÕES') AS MESES_DE_OPERACAO
FROM OPERADOR O
LEFT JOIN OPERACAO OP
ON O.CPF = OP.CPF AND OP.DATA_FIM > '01/01/2010'

Padrão SGBD:
SELECT O.NOME AS OPERADOR, NVL(TO_CHAR(MONTHS_BETWEEN(OP.DATA_FIM, OP.DATA_INICIO)), 'NÃO REALIZOU OPERAÇÕES') AS MESES_DE_OPERACAO
FROM   OPERADOR O, OPERACAO OP
WHERE  O.CPF = OP.CPF (+)
AND    OP.DATA_FIM (+) > '01/01/2010'


4)SELECT UPPER(TE.NOME_TIPO_EQPTO) AS NOME_TIPO_EQUIPAMENTO, 'R$' ||SUM(E.VALOR_EQPTO) AS VALOR_TOTAL_TIPO
FROM TIPO_EQUIPAMENTO TE
INNER JOIN EQUIPAMENTO E
ON E.CODIGO_TIPO_EQTO = TE.CODIGO_TIPO_EQTO
HAVING SUM(E.VALOR_EQPTO) > 500000
GROUP BY TE.NOME_TIPO_EQPTO
ORDER BY TE.NOME_TIPO_EQPTO

5)
SELECT O.NOME, G.NOME
FROM OPERADOR O
FULL OUTER JOIN GERENCIA G
ON O.SIGLA_GERENCIA = G.SIGLA

